FROM node:22-alpine AS builder

WORKDIR /app

COPY . .

RUN yarn install

ARG VITE_APP_BACKEND_API
ENV VITE_APP_BACKEND_API=$VITE_APP_BACKEND_API

RUN yarn build

FROM nginx:stable-alpine

COPY --from=builder /app/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]