FROM node:22-alpine@sha256:b6f26b36c8ff49624cfdac716b8ea1138d606df02586a77d364bb5536a634f85 AS builder
WORKDIR /app
COPY . .
RUN yarn install --frozen-lockfile
ARG VITE_APP_BACKEND_API
ENV VITE_APP_BACKEND_API=$VITE_APP_BACKEND_API
RUN yarn build

FROM nginx:1.27.3-alpine@sha256:814a8e88df978ade80e584cc5b333144b9372a8e3c98872d07137dbf3b44d0e4

COPY --from=builder /app/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80
ENTRYPOINT []
CMD ["nginx", "-g", "daemon off;"]