export const ROUTES_CONFIG = {
  AUTHENTICATION: {
    FORGOT_PASSWORD: "/auth/forgot-password",
    LOGIN: "/auth/login",
    RESET_PASSWORD: "/auth/reset-password",
    SIGNUP: "/auth/signup",
    CHANGE_PASSWORD: "/auth/change-password",
    MFA_SETUP: "/auth/mfa/setup",
    MFA_VERIFICATION: "/auth/mfa/verify",
  },
  USER: {
    CLIENT_DASHBOARD: "/client/dashboard",
    SOLO_DASHBOARD: "/solo/dashboard",
    ARCHIVE: "/archive",
    CASE_TYPE_SETUP: "/case-type-setup",
    FOLDER: "/folder",
    HOME: "/",
    MY_FILES: "/my-files",
    OFFICE_SETUP: "/office-setup",
    SHARED_WITH_ME: "/shared-with-me",
    USER_MANAGEMENT: "/user-management",
    USER_PROFILE: "/user-management/:userId/profile",
    USER_PERMISSIONS: "/user-management/:userId/permissions",
    USER_ACTIVITY: "/user-management/:userId/activity",
    ROLE_MANAGEMENT: "/role-management",
    ROLE_MANAGEMENT_DETAILS: "/role-management/:userId",
    MENU_MANAGEMENT: "/menu-management",
    PERMISSION_MANAGEMENT: "/permission-management",
    EMPLOYEE_MANAGEMENT: "/employee-management",
    FIRM_MANAGEMENT: "/firm-management",
    TASK_CALENDAR: "/task-calendar",
    CLIENT_MANAGEMENT: "/client-management",
    CASE_MANAGEMENT: "/case-management",
    CASE_MANAGEMENT_MATTERS: "/cases",
    CASE_MANAGEMENT_CREATE: "/cases/create",
    CASE_MANAGEMENT_DETAIL: "/cases/:matterNumber",
    CASE_MANAGEMENT_COURT_CASE:
      "/cases/:matterNumber/court-cases/:courtCaseRef",
    FIRM_ACTIVITY: "/firm-activity",
    STALE_MATTERS: "/stale-matters",
    SCRAPER_MANAGEMENT: "/scraper-management",
    GLOBAL_DASHBOARD: "/global-dashboard",
    PROJECT_MANAGEMENT: "/project-management",
    PROJECT_MANAGEMENT_PROJECTS: "/projects",
    PROJECT_MANAGEMENT_CREATE: "/projects/create",
    PROJECT_MANAGEMENT_EDIT: "/projects/:projectCode/edit",
    PROJECT_MANAGEMENT_DETAIL: "/projects/:projectCode",
    PROJECT_MANAGEMENT_RENEWAL_TYPES: "/projects/renewal-types",
    CLIENT_PROJECTS: "/client-projects",
    CLIENT_PROJECT_DETAIL: "/client-projects/:projectCode",
  },
  SUPER_ADMIN: {
    AUDIT_LOGS: "/super-admin/audit-logs",
    FIRM_MODULES: "/firm-management/:firmId/modules",
    FIRM_ACCESS_MANAGEMENT: "/firm-management/:firmId/access-management",
    GLOBAL_CONFIG: "/super-admin/configuration/global",
    FIRM_CONFIG: "/super-admin/configuration/firms",
  },

  NO_MATCH: "*",
};
