export const api = {
  login: "auth/login",
  signup: "auth/register/solo",
  refreshToken: "auth/refresh",
  loginClient: "auth/client/login",
  registerClient: "auth/register/client",
  superAdminLogin: "super-admin/login",
  changePassword: "auth/change-password",
  mfaSetupConfirm: "auth/mfa/setup/confirm",
  mfaValidate: "auth/mfa/validate",
  EMPLOYEE_MANAGEMENT: {
    GET_EMPLOYEES: "firm/employees",
    POST: "firm/employees",
    GET_BY_ID: "firm/employees/{employeeId}",
    PUT: "firm/employees/{employeeId}",
    TOGGLE: "firm/employees/{employeeId}/toggle",
    CHANGE_ROLE: "firm/employees/{employeeId}/role",
  },
  CONFIG_MANAGEMENT: {
    GET_GLOBAL: "super-admin/config",
    UPSERT_GLOBAL: "super-admin/config",
    DELETE_GLOBAL: "super-admin/config/{key}",
    GET_FIRM: "super-admin/firms/{firmId}/config",
    UPSERT_FIRM: "super-admin/firms/{firmId}/config",
  },
  CLIENT_MANAGEMENT: {
    GET_CLIENTS: "firm/clients",
    POST: "firm/clients",
    GET_BY_ID: "firm/clients/{clientId}",
    TOGGLE_PORTAL_ACCESS: "firm/clients/{clientId}/portal-access",
  },
  USER_MANAGEMENT: {
    ROLE_SETUP: {
      GET_ROLES: "admin/roles",
      ADD_EDIT: "admin/roles",
      GET_BY_ID: "admin/roles/{roleId}",
      TOGGLE: "admin/roles/{roleId}/toggle",
      DROPDOWN: "admin/roles/dropdown",
      ROLE_PERMISSIONS: "admin/roles/permissions",
      GET_ROLE_PERMISSIONS: "admin/roles/{roleId}/permissions",
      GET_ROLE_USERS: "firm/roles/{roleId}/users",
      DELETE: "admin/roles/{roleId}",
    },
    PERMISSION_SETUP: {
      GET_PERMISSIONS: "admin/permissions",
      GET_GROUPED_PERMISSIONS: "admin/permissions/grouped",
      POST: "admin/permissions",
      DELETE: "admin/permissions/{id}",
      TOGGLE: "admin/permissions/{id}/toggle",
      ACTIVE_PERMISSIONS: "admin/permissions/active",
      GET_BY_ID: "admin/permissions/{id}",
    },
    MENU_MANAGEMENT: {
      MODULE_MENUS: "admin/modules",
      GET_MODULES: "admin/modules",
      GET_BY_ID: "admin/modules/{moduleId}",
      DELETE: "admin/modules/{moduleId}",
      TOGGLE: "admin/modules/{moduleId}/toggle",
      PAGINATION: "admin/modules/pagination",
      LIST: "admin/modules/list",
      ASSIGN_PERMISSIONS: "admin/modules/{moduleId}/permissions",
    },
    USERS: {
      GET_USERS: "modules/users",
      SUPER_ADMIN_GET_USERS: "super-admin/users",
      SEARCH: "modules/users/search",
      GET_PROFILE: "modules/users/{userId}/profile",
      GET_PERMISSIONS: "modules/users/{userId}/permissions",
      GET_ACTIVITY: "modules/users/{userId}/activity",
      RESET_PASSWORD: "modules/users/{userId}/reset-password",
      BULK_ROLE_CHANGE: "modules/users/bulk-role-change",
      BULK_DEACTIVATE: "modules/users/bulk-deactivate",
      RESET_MFA: "super-admin/mfa/reset",
    },
  },
  FIRM_MANAGEMENT: {
    POST: "super-admin/firms",
    GET_FIRMS: "super-admin/firms/admins",
    GET_FIRMS_MODULES: "firm/modules",
    GET_FIRM_MODULES: "super-admin/firms/{firmId}/modules",
    CONFIGURE_FIRM_MODULE: "super-admin/firms/{firmId}/modules",
    GET_BY_ID: "super-admin/firms/{firmId}/admins",
    TOGGLE: "super-admin/firms/admins/{adminId}/toggle",
    GET_FIRM_ROLES: "firm/roles",
  },
  AUDIT_LOGS: {
    PLATFORM_AUDIT: "super-admin/audit",
    FIRM_AUDIT: "super-admin/audit/firms/{firmId}",
  },
  MATTER_MANAGEMENT: {
    GET_MATTERS: "firm/matters",
    POST: "firm/matters",
    GET_BY_MATTER_NUMBER: "firm/matters/{matterNumber}",
    PUT: "firm/matters/{matterNumber}",
    DELETE: "firm/matters/{matterNumber}",
    GET_TIMELINE: "firm/matters/{matterNumber}/timeline",
    GET_FIRM_TIMELINE: "firm/matters/timeline",
    GET_STALE: "firm/matters/stale",
    ADD_PARTY: "firm/matters/{matterNumber}/parties",
    MATCH_PARTY: "firm/matters/parties/match",
    ADD_COURT_CASE: "firm/matters/{matterNumber}/court-cases",
  },
  COURT_CASES: {
    GET_BY_REF: "firm/court-cases/{ourCourtCaseRef}",
    PUT: "firm/court-cases/{ourCourtCaseRef}",
    UPDATE_STAGE: "firm/court-cases/{ourCourtCaseRef}/stage",
    JUDGMENT: "firm/court-cases/{ourCourtCaseRef}/judgment",
    GET_EVENTS: "firm/court-cases/{ourCourtCaseRef}/events",
  },
  COURT_EVENTS: {
    GET: "firm/court-events/{eventId}",
    PUT: "firm/court-events/{eventId}",
    DELETE: "firm/court-events/{eventId}",
    HELD: "firm/court-events/{eventId}/held",
  },
  CALENDAR: {
    GET_EVENTS: "firm/calendar",
    GET_TODAY: "firm/calendar/today",
    GET_UPCOMING: "firm/calendar/upcoming",
  },
  SCRAPER: {
    CASE_HEARING_STATUS: "cases/{caseNoInternal}/hearing-status",
    ADMIN_SCRAPE: "scraper/admin/scrape",
    ADMIN_EXPORT: "scraper/admin/export",
  },
  DASHBOARD: {
    FIRM_DASHBOARD: "firm/dashboard",
    GLOBAL_DASHBOARD: "modules/dashboard",
  },
  MATTER_ASSIGNMENTS: {
    GET: "firm/matters/{matterNumber}/assignments",
    POST: "firm/matters/{matterNumber}/assignments",
    DELETE: "firm/matters/{matterNumber}/assignments/{userId}",
  },
  PROJECT_MANAGEMENT: {
    DASHBOARD: "projects/dashboard",
    PROJECTS: "projects",
    PROJECT_BY_CODE: "projects/{projectCode}",
    PROJECT_DELETE: "projects/{projectCode}",
    PROJECT_STATUS: "projects/{projectCode}/status",
    PROJECT_MEMBERS: "projects/{projectCode}/members",
    PROJECT_MEMBER_DELETE: "projects/{projectCode}/members/{userId}",
    PROJECT_CREDENTIALS: "projects/{projectCode}/credentials",
    CREDENTIAL_REVEAL: "projects/{projectCode}/credentials/{id}/reveal",
    CREDENTIAL_UPDATE: "projects/{projectCode}/credentials/{id}",
    CREDENTIAL_DELETE: "projects/{projectCode}/credentials/{id}",
    PROJECT_RENEWALS: "projects/{projectCode}/renewals",
    RENEWAL_DETAIL: "projects/{projectCode}/renewals/{id}",
    RENEWAL_UPDATE: "projects/{projectCode}/renewals/{id}",
    RENEWAL_STATUS: "projects/{projectCode}/renewals/{id}/status",
    RENEWAL_INSTANCE_UPDATE:
      "projects/{projectCode}/renewals/{renewalId}/instances/{instanceId}",
    RENEWAL_TYPES: "projects/renewal-types",
    RENEWAL_TYPE_UPDATE: "projects/renewal-types/{id}",
  },
  CLIENT_PROJECTS: {
    PROJECTS: "client/projects",
    PROJECT_BY_CODE: "client/projects/{projectCode}",
    PROJECT_RENEWALS: "client/projects/{projectCode}/renewals",
  },
  INVOICE_MANAGEMENT: {
    LIST: "super-admin/invoices",
    GET_BY_ID: "super-admin/invoices/{id}",
    CREATE: "super-admin/invoices",
    UPDATE: "super-admin/invoices/{id}",
    DELETE: "super-admin/invoices/{id}",
    SEND: "super-admin/invoices/{id}/send",
    UPDATE_STATUS: "super-admin/invoices/{id}/status",
    DOWNLOAD_PDF: "super-admin/invoices/{id}/pdf",
  },
};
