export const api = {
  login: "auth/login",
  signup: "auth/register/solo",
  refreshToken: "auth/refresh",
  loginClient: "auth/client/login",
  registerClient: "auth/register/client",
  superAdminLogin: "super-admin/login",
  EMPLOYEE_MANAGEMENT: {
    GET_EMPLOYEES: "firm/employees",
    POST: "firm/employees",
    GET_BY_ID: "firm/employees/{employeeId}",
    PUT: "firm/employees/{employeeId}",
    TOGGLE: "firm/employees/{employeeId}/toggle",
    CHANGE_ROLE: "firm/employees/{employeeId}/role",
  },
  CLIENT_MANAGEMENT: {
    GET_CLIENTS: "firm/clients",
    POST: "firm/clients",
    GET_BY_ID: "firm/clients/{clientId}",
    TOGGLE_PORTAL_ACCESS: "firm/clients/{clientId}/portal-access",
  },
  USER_MANAGEMENT: {
    ROLE_SETUP: {
      GET_ROLES: "admin/roles",
      ADD_EDIT: "admin/roles",
      GET_BY_ID: "admin/roles/{roleId}",
      TOGGLE: "admin/roles/{roleId}/toggle",
      DROPDOWN: "admin/roles/dropdown",
      ROLE_PERMISSIONS: "admin/roles/permissions",
      GET_ROLE_PERMISSIONS: "admin/roles/{roleId}/permissions",
    },
    PERMISSION_SETUP: {
      GET_PERMISSIONS: "admin/permissions",
      POST: "admin/permissions",
      DELETE: "admin/permissions/{id}",
      TOGGLE: "admin/permissions/{idd}/toggle",
      ACTIVE_PERMISSIONS: "admin/permissions/active",
      GET_BY_ID: "admin/permissions/{id}",
    },
    MENU_MANAGEMENT: {
      MODULE_MENUS: "admin/modules",
      GET_BY_ID: "admin/modules/{moduleId}",
      TOGGLE: "admin/modules/{moduleId}/toggle",
      PAGINATION: "admin/modules/pagination",
      LIST: "admin/modules/list",
      ASSIGN_PERMISSIONS: "admin/modules/{moduleId}/permissions",
    },
    USERS: {
      GET_USERS: "modules/users",
      SEARCH: "modules/users/search",
      GET_PROFILE: "modules/users/{userId}/profile",
      GET_PERMISSIONS: "modules/users/{userId}/permissions",
      GET_ACTIVITY: "modules/users/{userId}/activity",
      RESET_PASSWORD: "modules/users/{userId}/reset-password",
      BULK_ROLE_CHANGE: "modules/users/bulk-role-change",
      BULK_DEACTIVATE: "modules/users/bulk-deactivate",
    },
  },
  FIRM_MANAGEMENT: {
    POST: "super-admin/firms",
    GET_FIRMS: "super-admin/firms/admins",
    GET_FIRMS_MODULES: "firm/modules",
    GET_BY_ID: "super-admin/firms/{firmId}/admins",
    TOGGLE: "super-admin/firms/admins/{adminId}/toggle",
    GET_FIRM_ROLES:"firm/roles"
  },
  AUDIT_LOGS: {
    PLATFORM_AUDIT: "super-admin/audit/actions",
    FIRM_AUDIT: "super-admin/audit/firms/{firmId}",
  },
};
